export default {
  login: "asadbek2304",
  id: 76210602,
  node_id: "MDQ6VXNlcjc2MjEwNjAy",
  avatar_url: "https://avatars.githubusercontent.com/u/76210602?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/asadbek2304",
  html_url: "https://github.com/asadbek2304",
  followers_url: "https://api.github.com/users/asadbek2304/followers",
  following_url:
    "https://api.github.com/users/asadbek2304/following{/other_user}",
  gists_url: "https://api.github.com/users/asadbek2304/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/asadbek2304/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/asadbek2304/subscriptions",
  organizations_url: "https://api.github.com/users/asadbek2304/orgs",
  repos_url: "https://api.github.com/users/asadbek2304/repos",
  events_url: "https://api.github.com/users/asadbek2304/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/asadbek2304/received_events",
  type: "User",
  site_admin: false,
  name: "Asadbek Abduxoshimov",
  company: null,
  blog: "",
  location: "Uzbekistan, Tashkent",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2020-12-18T12:01:34Z",
  updated_at: "2021-04-20T09:37:02Z",
};
